[package]
name = "jsonrpc"
version = "0.11.0"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]
license = "CC0-1.0"
homepage = "https://github.com/apoelstra/rust-jsonrpc/"
repository = "https://github.com/apoelstra/rust-jsonrpc/"
documentation = "https://docs.rs/jsonrpc/"
description = "Rust support for the JSON-RPC 2.0 protocol"
keywords = [ "protocol", "json", "http", "jsonrpc" ]
readme	 = "README.md"
edition = "2018"

[features]
async = []

[lib]
name = "jsonrpc"
path = "src/lib.rs"

[dependencies]
base64-compat = "1.0.0"
http = "0.1"

serde = "1"
serde_derive = "1"
serde_json = "1"

